DROP TABLE IF EXISTS chat CASCADE;
CREATE TABLE chat (
    id SERIAL PRIMARY KEY NOT NULL,
    sender VARCHAR(255) NOT NULL,
    receiver VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL,
    sent_at TIMESTAMP NOT NULL DEFAULT now()
);